### ISSUE TITLE
Spieler starten mit unterschiedlichen Startpunkten

### ISSUE THREAD

**Issue by FrederikSchlemmer** [adessoSE/BrainySnake#10]
Die Spieler starten teilweise mit einem Punkt mehr als in der Config definiert.

![unbenannt](https://user-images.githubusercontent.com/35023083/35151902-6100fc40-fd20-11e7-86d9-0a1b002d7cf8.PNG)

**Comment by RudiKlassen-zz** [comment]
Das liegt möglicherweise daran, dass die auf einem Punkt spawnen. Ist aber
nur eine Vermutung.

2018-01-19 13:55 GMT+01:00 FrederikSchlemmer <notifications@github.com>:

**Comment by FrederikSchlemmer** [comment]
Das Problem liegt in der SamplePlayer Klasse, welche durch die vorhandene Schleife in der vorgegebenen Zeitspanne kein PlayerUpdate als Antwort sendet.
Dadurch erhält der Spieler im ersten Durchlauf direkt eine Bestrafung. Dementsprechend ist das Problem eine zu hohe Spielerpunkteanzahl. 

Aktuell:
`for (int i = 0; i <= initialLength; i++) {`

Vorschlag:
`for (int i = 1; i <= initialLength; i++) {`

Hierdurch wird die definierte Spielerlänge erreicht:
`public static final int INITIAL_PLAYER_LENGTH = 5;`

![unbenannt](https://user-images.githubusercontent.com/35023083/35269247-c40a7e8e-002b-11e8-907f-cceb66b33187.PNG)

**Comment by RudiKlassen-zz** [comment]
Ok, SamplePlayer wird durch neuen Agenten ersetzt. Daher kann das Ticket geschlossen werden.
