### ISSUE TITLE
Kopf der Schlange befindet sich nicht im ViewField

### ISSUE THREAD

**Issue by dariobraun** [adessoSE/BrainySnake#15]
Falls es so gedacht ist, dass der Kopf der Schlange das 22. Feld des ViewFields darstellt, muss dies noch angepasst werden. Momentan befindet sich der Kopf außerhalb des ViewField

**Comment by RudiKlassen-zz** [comment]
Hi Dario,
siehe dazu die Abbildung unter Spielregeln in unserer Readme (
https://github.com/adessoAG/BrainySnake).
Das Sichtfeld sollte sich genau vor dem Kopf der Schlange befinden. Müsste
also passen.

Viele grüße
Rudi

Am 25. Januar 2018 um 11:30 schrieb Dario Braun <notifications@github.com>:

**Comment by dariobraun** [comment]
Alles klar,
die Kommentare im Code sind, was das angeht, etwas widersprüchlich, aber die Doku passt - Dann weiß ich Bescheid!
