### ISSUE TITLE
Soll eine Schlange sterben, wenn nur noch der Kopf vorhanden ist?

### ISSUE THREAD

**Issue by dariobraun** [adessoSE/BrainySnake#16]
Oder soll eine Schlange erst sterben, sobald der Kopf als letztes Element verschwindet?

**Comment by RudiKlassen-zz** [comment]
Ich finde es sähe eigenartig aus, wenn nur ein einzelner Punkt unterwegs wäre. Daher würde ich die Frage mit Ja beantworten. Fall von eurer Seite nichts dagegen spricht, bitte umsetzen. @dariobraun  Könntest du dazu bitte einen Task anlegen?

**Comment by dariobraun** [comment]
Aktuell ist es so umgesetzt, dass die Schlange stirbt, wenn der letzte Teil des _Körpers_ verschwindet. Also alles so, wie gewollt!

**Comment by dariobraun** [comment]
Aktuell ist es so umgesetzt, dass die Schlange stirbt, wenn der letzte Teil des Körpers verschwindet. Also alles so, wie gewollt!
