### ISSUE TITLE
Methode zum Ausgeben des aktuellen Spielers und dessen Sicht in die Console

### ISSUE THREAD

**Issue by RudiKlassen-zz** [adessoSE/BrainySnake#2]

**Comment by dariobraun** [comment]
Könntet ihr etwas genauer erläutern, was hiermit gemeint ist?

**Comment by RudiKlassen-zz** [comment]
Hi Dario,
es wäre super, wenn man während der Entwicklung für Testzwecke in der Console sehen könnte,  was der Spieler im Match grad sieht. Auf diese Weise kann man im nachhinein Schritt für Schritt nachvollziehen, wie der Spieler sich während des Spiels verhalten hat. Dafür benötigen wir eine geeignete Ausgabe in der Console. 
Für eine spätere Version wäre es natürlich besser eine Art Debug-Mode im Spiel zu haben und die einzelnen Frames manuell zu steuern, was aber etwas aufwändiger wäre. 

Sag bescheid, wenn dir hier noch bessere Möglichkeiten einfallen.
