### ISSUE TITLE
PlayerState: PlayerTail im PlayerState als Point2D anstatt LinkedList<Point2D>

### ISSUE THREAD

**Issue by FrederikSchlemmer** [adessoSE/BrainySnake#7]
Abfrage des Spieler aus dem PlayerState gibt den PlayerTail als einzelnen Point2D wieder. Dieser Punkt bezieht sich desweiteren auf den Kopf der Schlange.
Eine Rückgabe als LinkedList zur gesamten Übersicht der Schlange wäre sinnvoll.

**Comment by FlorianTim** [comment]
Das ist so beabsichtigt. Wir wollten es den Teilnehmern nicht zu leicht machen. Zudem sollen Teilnehmer mit weniger Erfahrung (z.B. Schüler) kleine Erfolge erziehen, indem sie Basisfunktionen implementieren. 

Die Implementierung eines intelligenten Agenten ist daher der zweite Schritt, wenn der Spieler in der Lage ist seinen eigenen Status zu verwalten. Daher ist, die „API“ absichtlich begrenzt.

**Comment by FrederikSchlemmer** [comment]
Ebenfalls beabsichtigt ist die Ausgabe der Position von dem Schlangenkopf bei dem Aufruf der Schlangenkörper-Position?

Aktuell:
`Point2D head = new Point2D(snake.getHeadPosition());`
`Point2D tail  = new Point2D(snake.getHeadPosition());`

Vorschlag:
`Point2D head = new Point2D(snake.getHeadPosition());`
`Point2D tail  = new Point2D(snake.getTailPosition());`

**Comment by FlorianTim** [comment]
Nein, das ist wohl ein Bug. :)
Darst du gerne korrigieren.

Gemeint ist immer genau das letzte Element. Das müssen wir vielleicht in der Dokumentation noch hervorheben
