### ISSUE TITLE
Snake head reaches into FOV due to "lag"

### ISSUE THREAD

**Issue by dariobraun** [adessoSE/BrainySnake#75]
The Snake's head is (or at least looks to be) part of the FOV instead of being outside the FOV, as intended. Not sure if this has any real drawbacks or is just being displayed delayed/wrong.

![unbenannt](https://user-images.githubusercontent.com/29201552/36468640-79fcf6f8-16e4-11e8-9ed3-ce6408a30838.PNG)

**Comment by FrederikSchlemmer** [comment]
Maybe related to #72?

**Comment by AlexanderBrockmann** [comment]
What means FOV?
