### ISSUE TITLE
Game lags when player takes too long to respond

### ISSUE THREAD

**Issue by dariobraun** [adessoSE/BrainySnake#77]
"Slowest" player determines game update. E.g. when a player takes >500ms to respond, the whole game will have a significant delay.
Possible solution: Limit players to a response time of 100ms by configuring `MAX_AGENT_PROCESSING_TIME_MS` in config.
Drawbacks: Complex algorithms might not be viable.

**Comment by AlexanderBrockmann** [comment]
Should not occur anymore
